title: "Lexie Gardner"
description: ""
baseurl: ""                     # leave empty unless your site is in a subfolder
url: "https://lexiegardner.github.io" 
email: lexie.gardner@berkeley.edu
repository: lexiegardner/lexiegardner.github.io  

remote_theme: "mmistakes/minimal-mistakes@4.24.0" 
minimal_mistakes_skin: "default"

author:
  name: "Lexie Gardner"
  avatar: "/assets/images/bio-photo.JPG"  
  bio: "PhD Student<br>University of California, Berkeley<br>lexie.gardner@berkeley.edu"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:lexie.gardner@berkeley.edu"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=1bUVIDIAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lexiegardner"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/lexie-gardner-376527212"
      
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lexiegardner"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:lexie.gardner@berkeley.edu"

markdown: kramdown
kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true  # this enables the left sidebar everywhere
include:
  - _pages
